
function getRandomNumber(){
return new Promise((resolve,reject)=>{
   const flag = false;
   if(!flag){
   resolve(setTimeout(()=>{
      const x = Math.floor(Math.random()*10)
      console.log(x)
   },500)
   )
   }else{
   reject("Error Message")
   }

})
}
async function getNumber(){
  await getRandomNumber()
  //console.log(y)
//   console.log(y)
}

getNumber();